import { ArtistProfile, Commission, Order, CustomerUser } from './types';

export const INITIAL_ARTIST: ArtistProfile = {
  name: 'Peti',
  handle: '@peti_art',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  bio: 'A full-time VTuber mama, and a professional anime-style character designer who has been in the field for more than 10 years and has more than 900 five-star reviews on other commission platforms.',
  rating: 4.98,
  reviewsCount: 942,
  totalCompletedCommissions: 1280,
  socialLinks: [
    { platform: 'twitter', label: 'Twitter / X', url: 'https://twitter.com' },
    { platform: 'instagram', label: 'Instagram', url: 'https://instagram.com' },
    { platform: 'artstation', label: 'ArtStation', url: 'https://artstation.com' },
    { platform: 'discord', label: 'Discord Server', url: 'https://discord.com' },
    { platform: 'website', label: 'Portfolio Personal', url: 'https://peti.art' },
  ],
};

export const INITIAL_CUSTOMERS: CustomerUser[] = [
  {
    id: 'usr-alex',
    name: 'Alex Rivers',
    email: 'alex.rivers@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    discord: 'alex_rivers#1337',
    role: 'customer',
    createdAt: '2026-08-16T15:30:00Z',
  },
  {
    id: 'usr-valeria',
    name: 'Valeria Gomez',
    email: 'valeria.g@outlook.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    discord: 'valeria_vtuber',
    role: 'customer',
    createdAt: '2026-08-14T10:15:00Z',
  },
  {
    id: 'usr-marcus',
    name: 'Marcus Bennett',
    email: 'marcus.b@creative.io',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
    discord: 'marcus_streamer',
    role: 'customer',
    createdAt: '2026-08-12T18:45:00Z',
  },
  {
    id: 'usr-sofia',
    name: 'Sofia Martinez',
    email: 'sofi.mtz@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    discord: 'sofia_m',
    role: 'customer',
    createdAt: '2026-08-01T12:00:00Z',
  },
];

export const INITIAL_COMMISSIONS: Commission[] = [
  {
    id: 'comm-1',
    title: 'Half body to fullbody anime style character art',
    slug: 'half-to-fullbody-anime-character',
    priceMin: 95,
    priceMax: 295,
    slotsAvailable: 1,
    deliveryDays: 14,
    description: 'Detailed illustrative anime character artwork. Ideal for original characters (OCs), fanarts, banner illustrations, and profile art.',
    samples: [
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=600&q=80',
    ],
    additionalInfo: [
      'More art samples, visit my website: www.peti.art',
      'Full NSFW is ok too. Contact me before you place the order.',
      'If what you are looking for is not in this page, please contact me for a quote ^^',
      'Price is for personal use only. Includes 2 sketch revisions and 1 color revision after completed.',
      'Commercial rights available as an extra add-on.',
    ],
    options: [
      { id: 'opt-1-1', name: 'Fullbody Upgrade', price: 100, description: 'Renders the full character body head to toe' },
      { id: 'opt-1-2', name: 'Detailed Complex Background', price: 60, description: 'Architecture, fantasy landscape or complex room' },
      { id: 'opt-1-3', name: 'Commercial Rights License', price: 120, description: 'Includes rights for merchandising, stream assets & promotion' },
      { id: 'opt-1-4', name: 'Extra Character (+1)', price: 80, description: 'Adds a second character interacting in the same canvas' },
      { id: 'opt-1-5', name: 'Rush Delivery (7 days)', price: 50, description: 'Priority in the queue with 7 days turnaround' },
    ],
    active: true,
    category: 'Illustration',
  },
  {
    id: 'comm-2',
    title: 'Vtuber model (rigging not included)',
    slug: 'vtuber-model-rig-ready',
    priceMin: 500,
    priceMax: 750,
    slotsAvailable: 3,
    deliveryDays: 30,
    description: 'High resolution, cut and organized layered PSD ready for Live2D rigging. Designed specifically for aspiring and professional streamers.',
    samples: [
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1569705460033-cfaa4bf9f822?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
    ],
    additionalInfo: [
      'More art samples, visit my website: www.peti.art',
      'Please note that this is for model creating only (with rigging ready layering PSD).',
      'Rigging is NOT included. I do have a partnered rigger to recommend if you need one.',
      'Includes 3 expression toggles (Blush, Teary, Angry).',
      'Includes commercial rights for streaming and branding.',
    ],
    options: [
      { id: 'opt-2-1', name: '3 Extra Expressions (Heart eyes, Shock, Pout)', price: 75, description: 'Extra emotional toggles for Live2D' },
      { id: 'opt-2-2', name: 'Alternate Hairstyle / Jacket Toggle', price: 150, description: 'Layered separate hair/outfit toggle' },
      { id: 'opt-2-3', name: 'Chibi Mascot / Pet companion', price: 90, description: 'Matching layered stream mascot' },
      { id: 'opt-2-4', name: 'Character Reference Sheet Turnaround', price: 180, description: 'Front, back and detail view sheet' },
    ],
    active: true,
    category: 'VTuber',
  },
  {
    id: 'comm-3',
    title: 'Chibi character & emotes pack',
    slug: 'chibi-character-emotes-pack',
    priceMin: 45,
    priceMax: 120,
    slotsAvailable: 4,
    deliveryDays: 7,
    description: 'Super cute chibi illustration or custom Twitch/Discord emotes pack in all required PNG sizes (28px, 56px, 112px + 500px HD).',
    samples: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1569705460033-cfaa4bf9f822?auto=format&fit=crop&w=600&q=80',
    ],
    additionalInfo: [
      'Delivered in transparent PNGs ready for Twitch, Discord and YouTube.',
      'Commercial streaming rights included by default.',
      'Unlimited minor adjustments during the sketch phase.',
    ],
    options: [
      { id: 'opt-3-1', name: 'Pack of 3 Emotes', price: 35, description: '3 custom expressions/poses' },
      { id: 'opt-3-2', name: 'Pack of 6 Emotes', price: 65, description: '6 custom expressions/poses' },
      { id: 'opt-3-3', name: 'Animated GIF / APNG Emote (+1)', price: 40, description: 'Looping bounce/wave/cry animation' },
    ],
    active: true,
    category: 'Emotes',
  },
  {
    id: 'comm-4',
    title: 'NSFW no limit uncensored anime style art',
    slug: 'nsfw-no-limit-anime-art',
    priceMin: 95,
    priceMax: 395,
    slotsAvailable: 2,
    deliveryDays: 14,
    description: 'Explicit, sensual and highly detailed 18+ illustrations. All genres, pairings, and fetishes welcome with no taboos. Delivered with high-res PSD and alt versions.',
    samples: [
      'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    ],
    additionalInfo: [
      'Strictly 18+ only. Buyer certifies being of legal age.',
      'Multiple outfits, expression, and fluids variations available.',
      'PSD with organized layers included for higher tiers.',
    ],
    options: [
      { id: 'opt-4-1', name: 'Clothing / Outfit Alt Variation', price: 45, description: 'Separate PNG with alternate or removed clothing' },
      { id: 'opt-4-2', name: 'Expression Variations Pack (3)', price: 30, description: '3 extra facial expressions' },
      { id: 'opt-4-3', name: 'Full PSD File Included', price: 50, description: 'Source file with intact uncensored layer groups' },
    ],
    active: true,
    category: '18+ NSFW',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: '#PETI-8901',
    customerId: 'usr-alex',
    customerName: 'Alex Rivers',
    customerEmail: 'alex.rivers@gmail.com',
    total: 275,
    paymentMethod: 'mercadopago',
    status: 'pending',
    createdAt: '2026-08-16T15:30:00Z',
    estimatedDelivery: '2026-08-30',
    notes: 'Quiero un personaje femenino con cabello plateado y ojos violetas estilo cyberpunk con fondo de neón.',
    items: [
      {
        id: 'cart-item-1',
        commissionId: 'comm-1',
        title: 'Half body to fullbody anime style character art',
        unitPrice: 275,
        quantity: 1,
        sampleImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
        selectedOptionNames: ['Fullbody Upgrade ($100)', 'Detailed Complex Background ($60)'],
        commissionData: {
          usageType: 'personal',
          brief: 'Personaje femenino anime estilo cyberpunk, guantes mecánicos y fondo de calle lluviosa con luces de neón rosa y azul.',
          references: 'https://pinterest.com/pin/example-cyberpunk-girl',
          selectedOptions: ['opt-1-1', 'opt-1-2'],
          customerName: 'Alex Rivers',
          customerEmail: 'alex.rivers@gmail.com',
        },
      },
    ],
  },
  {
    id: 'ord-102',
    orderNumber: '#PETI-8902',
    customerId: 'usr-valeria',
    customerName: 'Valeria Gomez',
    customerEmail: 'valeria.g@outlook.com',
    total: 725,
    paymentMethod: 'polar',
    status: 'in_progress',
    createdAt: '2026-08-14T10:15:00Z',
    estimatedDelivery: '2026-09-13',
    notes: 'Modelo Vtuber temática gato espacial para debut en Twitch a finales de septiembre.',
    items: [
      {
        id: 'cart-item-2',
        commissionId: 'comm-2',
        title: 'Vtuber model (rigging not included)',
        unitPrice: 725,
        quantity: 1,
        sampleImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
        selectedOptionNames: ['3 Extra Expressions ($75)', 'Chibi Mascot ($90)', 'Alternate Hairstyle ($150)'],
        commissionData: {
          usageType: 'commercial',
          brief: 'Chica gato galáctica con orejas esponjosas, traje de astronauta pastel y mascota flotante estelar.',
          references: 'https://imgur.com/gallery/space-cat-refs',
          selectedOptions: ['opt-2-1', 'opt-2-2', 'opt-2-3'],
          customerName: 'Valeria Gomez',
          customerEmail: 'valeria.g@outlook.com',
        },
      },
    ],
  },
  {
    id: 'ord-103',
    orderNumber: '#PETI-8903',
    customerId: 'usr-marcus',
    customerName: 'Marcus Bennett',
    customerEmail: 'marcus.b@creative.io',
    total: 110,
    paymentMethod: 'mercadopago',
    status: 'in_review',
    createdAt: '2026-08-12T18:45:00Z',
    estimatedDelivery: '2026-08-19',
    notes: 'Emotes de zorro para canal de Twitch verificado. Boceto ya aprobado, revisando paleta de color.',
    items: [
      {
        id: 'cart-item-3',
        commissionId: 'comm-3',
        title: 'Chibi character & emotes pack',
        unitPrice: 110,
        quantity: 1,
        sampleImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
        selectedOptionNames: ['Pack of 6 Emotes ($65)'],
        commissionData: {
          usageType: 'commercial',
          brief: '6 emotes de zorro: GG, Hype, Llorando, Rage, Café y Lurk.',
          references: 'https://drive.google.com/drive/folders/fox-emotes-ref',
          selectedOptions: ['opt-3-2'],
          customerName: 'Marcus Bennett',
          customerEmail: 'marcus.b@creative.io',
        },
      },
    ],
  },
  {
    id: 'ord-104',
    orderNumber: '#PETI-8904',
    customerId: 'usr-sofia',
    customerName: 'Sofia Martinez',
    customerEmail: 'sofi.mtz@gmail.com',
    total: 175,
    paymentMethod: 'polar',
    status: 'completed',
    createdAt: '2026-08-01T12:00:00Z',
    estimatedDelivery: '2026-08-15',
    notes: 'Retrato de pareja estilo anime para aniversario entregado en alta resolución 300 DPI.',
    items: [
      {
        id: 'cart-item-4',
        commissionId: 'comm-1',
        title: 'Half body to fullbody anime style character art',
        unitPrice: 175,
        quantity: 1,
        sampleImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
        selectedOptionNames: ['Extra Character (+1) ($80)'],
        commissionData: {
          usageType: 'personal',
          brief: 'Pareja abrazándose en un atardecer estilo película de Makoto Shinkai.',
          references: 'https://drive.google.com/drive/folders/couple-ref',
          selectedOptions: ['opt-1-4'],
          customerName: 'Sofia Martinez',
          customerEmail: 'sofi.mtz@gmail.com',
        },
      },
    ],
  },
];
